<?php
/**
 * Access protected
 * Author: Sergii Zazymko
 * Date: 27.10.18
 * Time: 21:03
 */

$title = 'Delete album';

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($album->getTitle()) ?>" by
    "<?= $this->escapeHtml($album->getArtist()) ?>"?
</p>

<form method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $album->getId() ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
</div>
</form>