<?php
/**
 * Access protected
 * Author: Sergii Zazymko
 * Date: 27.10.18
 * Time: 21:03
 */

$title = 'My albums';
$this->headTitle($title);
$this->headScript()->prependFile('/assets/confirm.js');

?>

<h1><?= $this->escapeHtml($title); ?></h1>
<a href="<?= $this->url('album', ['action' => 'add']); ?>">Add new album</a>
<p>
    <a href="<?= $this->url('album', ['action' => 'add']); ?>"></a>
</p>

<table class="table">
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>


    <?php /** @var \Album\Entity\Album $album */
    foreach ($this->albums as $album) : ?>
        <tr>
            <td><?= $this->escapeHtml($album->getTitle()); ?></td>
            <td><?= $this->escapeHtml($album->getArtist()); ?></td>
            <td>
                <a href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->getId()]); ?>">
                    Edit
                </a> |
                <a href="<?= $this->url('album', ['action' => 'delete', 'id' => $album->getId()]); ?>" class="delete">
                    Delete
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
